### PR TITLE
Changed check for max size

### PR DESCRIPTION
**Pull request by nieldk**
The check-size was incorrect, this makes it calculate correct size

### CODE REVIEW

**Comment by iceman1001** [comment]
Nice fix!
Your branch which you based your PR seem to have a conflict.

**Comment by nieldk** [comment]
> Nice fix!
> Your branch which you based your PR seem to have a conflict.

Hmm false-positive, but, the chip identifier was not needed. Fixed

**Comment by iceman1001** [comment]
... it looks like you had not pull latest before making this PR.   Now there is a heap of changes not belonging to this PR.
May I suggest you close this PR,   and just commit that Makefile changes in a new PR?

**Comment by nieldk** [comment]
Doing it again :)

**Pull request closed without merging**
